name: Replica
version: '1.1.0-BETA'
main: me.drawn.replica.Replica
api-version: '1.20'
author: Drawn
folia-supported: true
softdepend:
  - ModelEngine
  - MegaVerse # Load after MegaVerse world import
commands:
  replica:
    aliases:
      - npc
      - rnpc
      - npcs